services:
  - type: web
    name: cloneapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne cloneapp.asgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: cloneapp.settings

