services:
  - type: web
    name: base
    env: python 
    buildCommand : pip install -r requirements.txt
    startCommand: daphne cloneapp.asgi : application
envVars :
  - key: DATABASE_URL
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DEBUG
    value: False
