# Generated by Django 5.1.3 on 2025-01-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rooms',
            new_name='Room',
        ),
    ]
