# Generated by Django 5.1.3 on 2025-01-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topic_message_room_topic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
