# Generated by Django 5.1.3 on 2025-01-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
