# Generated by Django 5.1.3 on 2025-03-20 14:37

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_photo_description_remove_photo_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(default='o2pachscqy1o3ys4j0sw', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dp', to=settings.AUTH_USER_MODEL),
        ),
    ]
